services:
  gitlab-jira-hook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-docker}
        COMMIT: ${COMMIT:-unknown}
        DATE: ${DATE:-}
        BUILT_BY: ${BUILT_BY:-docker-compose}
    image: gitlab-jira-hook:${VERSION:-latest}
    container_name: gitlab-jira-hook
    restart: unless-stopped
    ports:
      - "9988:8080"
    env_file:
      - config.env
    volumes:
      # Mount logs directory for persistent logs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s