services:
  gitlab-jira-hook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-docker}
        COMMIT: ${COMMIT:-unknown}
        DATE: ${DATE:-}
        BUILT_BY: ${BUILT_BY:-docker-compose}
    image: gitlab-jira-hook:${VERSION:-latest}
    container_name: gitlab-jira-hook
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - config.env
    volumes:
      # Mount logs directory for persistent logs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Simple nginx reverse proxy for localhost
  nginx:
    image: nginx:alpine
    container_name: gitlab-jira-hook-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gitlab-jira-hook
    profiles:
      - nginx 