services:
  gitlab-jira-hook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-docker}
        COMMIT: ${COMMIT:-unknown}
        DATE: ${DATE:-}
        BUILT_BY: ${BUILT_BY:-docker-compose}
    image: gitlab-jira-hook:${VERSION:-latest}
    container_name: gitlab-jira-hook
    restart: unless-stopped
    ports:
      - "9988:8080"
    env_file:
      - config.env
    environment:
      # Set timezone from config or use default
      - TZ=${TIMEZONE:-Etc/GMT-5}
    volumes:
      # Mount logs directory for persistent logs
      - ./logs:/app/logs
      # Mount timezone data for container timezone support
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 256M